[package]
rust-version.workspace = true
name = "sdkwork-api-notary-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-notary application HTTP plane."


[lints]
workspace = true
[lib]
name = "sdkwork_api_notary_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork-notary-embedded-bootstrap.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-routes-notary-app-api.workspace = true
sdkwork-routes-notary-backend-api.workspace = true
