-- SDKWork notary consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_notary_baseline.sql
-- sdkwork:migration
-- id: 0001_notary_foundation
-- engine: postgres
-- module: notary
-- purpose: Create notary foundation tables and indexes
-- reversible: true
-- transactional: true
-- lock: lightweight
-- contract_version: 1.0.0

-- SDKWork Notary foundation schema.
--
-- Reused systems of record:
-- - IAM/Appbase: iam_organization, iam_organization_membership, iam_role,
--   iam_position, iam_department.
-- - Commerce: commerce_product_sku, commerce_order, commerce_order_item.
-- - Drive: dr_drive_space, dr_drive_node.
--
-- Cross-service references are logical references. Do not add physical foreign
-- keys to dependency-owned tables; sdkwork-notary validates them through the
-- corresponding SDK/service boundary.

CREATE TABLE IF NOT EXISTS notary_organization_profile (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  status TEXT NOT NULL CHECK (status IN ('active', 'suspended', 'closed')),
  drive_space_id TEXT NOT NULL,
  drive_space_type TEXT NOT NULL DEFAULT 'notary' CHECK (drive_space_type = 'notary'),
  opened_by_membership_id TEXT,
  opened_at TEXT NOT NULL,
  suspended_at TEXT,
  closed_at TEXT,
  settings_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (tenant_id, organization_id)
);

CREATE TABLE IF NOT EXISTS notary_case (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  case_no TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  remarks TEXT,
  status TEXT NOT NULL CHECK (
    status IN (
      'pending_review',
      'processing',
      'completed',
      'rejected',
      'cancelled',
      'create_failed'
    )
  ),
  applicant_user_id TEXT NOT NULL,
  applicant_name_snapshot TEXT NOT NULL,
  primary_notary_membership_id TEXT,
  primary_notary_user_id TEXT,
  primary_notary_name_snapshot TEXT,
  order_id TEXT NOT NULL,
  order_item_id TEXT NOT NULL,
  sku_id TEXT NOT NULL,
  matter_title_snapshot TEXT NOT NULL,
  fee_amount_snapshot TEXT NOT NULL,
  currency_code TEXT NOT NULL,
  drive_space_id TEXT NOT NULL,
  drive_space_type TEXT NOT NULL DEFAULT 'notary' CHECK (drive_space_type = 'notary'),
  drive_folder_node_id TEXT NOT NULL,
  chain_hash TEXT,
  risk_level TEXT,
  review_result TEXT,
  reject_reason TEXT,
  submitted_at TEXT NOT NULL,
  accepted_at TEXT,
  completed_at TEXT,
  rejected_at TEXT,
  request_no TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  UNIQUE (tenant_id, case_no),
  UNIQUE (tenant_id, order_id),
  UNIQUE (tenant_id, order_item_id),
  UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS notary_party (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  case_id TEXT NOT NULL,
  order_id TEXT NOT NULL,
  order_item_id TEXT NOT NULL,
  sku_id TEXT NOT NULL,
  party_role TEXT NOT NULL,
  party_type TEXT NOT NULL DEFAULT 'natural_person',
  name TEXT NOT NULL,
  identity_type TEXT NOT NULL DEFAULT 'resident_identity_card',
  identity_no_hash TEXT NOT NULL,
  identity_no_encrypted TEXT NOT NULL,
  identity_no_last4 TEXT NOT NULL,
  phone_encrypted TEXT,
  phone_masked TEXT,
  gender TEXT,
  birth_date TEXT,
  address_encrypted TEXT,
  address_snapshot TEXT,
  identity_valid_date_start TEXT,
  identity_valid_date_end TEXT,
  verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (
    verification_status IN ('pending', 'verified', 'failed', 'expired')
  ),
  face_compare_score TEXT,
  verified_at TEXT,
  party_folder_node_id TEXT,
  id_front_node_id TEXT,
  id_back_node_id TEXT,
  face_image_node_id TEXT,
  signature_node_id TEXT,
  remarks TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'removed')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS notary_case_assignment (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  case_id TEXT NOT NULL,
  organization_membership_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  assignment_role TEXT NOT NULL CHECK (
    assignment_role IN ('primary_notary', 'assistant', 'reviewer', 'approver')
  ),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'released')),
  assigned_by_membership_id TEXT,
  assigned_at TEXT NOT NULL,
  released_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, case_id, organization_membership_id, assignment_role)
);

CREATE TABLE IF NOT EXISTS notary_case_event (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT '0',
  case_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  event_title TEXT NOT NULL,
  event_detail TEXT,
  actor_user_id TEXT,
  actor_membership_id TEXT,
  actor_display_name TEXT,
  occurred_at TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notary_organization_profile_status
  ON notary_organization_profile (tenant_id, organization_id, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_notary_case_org_status_updated
  ON notary_case (tenant_id, organization_id, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_notary_case_primary_notary
  ON notary_case (tenant_id, organization_id, primary_notary_membership_id, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_notary_case_sku_status
  ON notary_case (tenant_id, organization_id, sku_id, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_notary_case_drive_folder
  ON notary_case (tenant_id, drive_space_type, drive_space_id, drive_folder_node_id);

CREATE INDEX IF NOT EXISTS idx_notary_party_case_sort
  ON notary_party (tenant_id, case_id, status, sort_order);

CREATE INDEX IF NOT EXISTS idx_notary_party_order
  ON notary_party (tenant_id, order_id);

CREATE INDEX IF NOT EXISTS idx_notary_party_sku_status
  ON notary_party (tenant_id, organization_id, sku_id, status);

CREATE INDEX IF NOT EXISTS idx_notary_party_identity_hash
  ON notary_party (tenant_id, identity_no_hash);

CREATE INDEX IF NOT EXISTS idx_notary_case_assignment_member
  ON notary_case_assignment (
    tenant_id,
    organization_id,
    organization_membership_id,
    status,
    assigned_at
  );

CREATE INDEX IF NOT EXISTS idx_notary_case_assignment_case
  ON notary_case_assignment (tenant_id, case_id, status);

CREATE INDEX IF NOT EXISTS idx_notary_case_event_case_time
  ON notary_case_event (tenant_id, case_id, occurred_at);
