environment = "test"

[http]

[[http.server]]
listen = ["80"]
serverName = ["notary-test.sdkwork.com", "notary-test.birdcoder.com", "notary-test.dtupay.com", "notary-test.noaper.com", "notary-test.sdkwork.cn", "notary-test.birdcoder.cn", "notary-test.dtupay.cn", "notary-test.noaper.cn", "notary-test.skubc.com", "notary-test.skubc.cn", "notary-test.zowalk.com", "notary-test.zowalk.cn", "notary-test.offer86.com", "notary-test.offer86.cn", "notary-test.86offer.com", "notary-test.86offer.cn", "notary-admin-test.sdkwork.com", "notary-admin-test.birdcoder.com", "notary-admin-test.dtupay.com", "notary-admin-test.noaper.com", "notary-admin-test.sdkwork.cn", "notary-admin-test.birdcoder.cn", "notary-admin-test.dtupay.cn", "notary-admin-test.noaper.cn", "notary-admin-test.skubc.com", "notary-admin-test.skubc.cn", "notary-admin-test.zowalk.com", "notary-admin-test.zowalk.cn", "notary-admin-test.offer86.com", "notary-admin-test.offer86.cn", "notary-admin-test.86offer.com", "notary-admin-test.86offer.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.nonproduction.conf"]

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

